import { spawn } from 'node:child_process';
import { posix } from 'node:path';

import { CliError } from './errors.js';

/**
 * Running a project on this machine, in the same container image the cloud runs.
 *
 * The point is a loop that costs nothing: put your files, your environment and your
 * soul into the runtime, run your setup, run your test, and read what the agent does,
 * before a server exists anywhere. The image is the pinned one the platform itself
 * deploys, pulled by tag from a public registry, so the thing being exercised is not
 * an approximation of the runtime.
 *
 * What a local run deliberately does not do is render the runtime's own config. On
 * the cloud that file is generated by the backend and holds decisions no project
 * makes: the approvals mode, the website blocklist, which toolsets each platform
 * gets. Writing a second copy of that logic out here is how the two drift, and a
 * drifted copy passes locally and fails when deployed, which is worse than not
 * having the feature. So a local container keeps the runtime's own defaults, and
 * `agent run` says so in as many words. Everything a project actually declares is
 * applied exactly as the cloud applies it.
 */

export interface ShellResult {
  stdout: string;
  stderr: string;
  code: number;
}

/**
 * How this module reaches Docker. Injected rather than imported so a test can run the
 * whole command against a recorded transcript, on a machine with no Docker at all.
 */
export type Shell = (args: readonly string[], stdin?: string) => Promise<ShellResult>;

/**
 * `spawn` rather than `execFile`, because of stdin.
 *
 * A file reaches the container by being piped into `cat` inside it, which needs the
 * pipe closed afterwards or `cat` waits for more and the command never returns.
 * `execFile` has no way to say that, so this collects the streams by hand. A non-zero
 * exit is a result rather than a throw: most of what this module asks Docker is a
 * question whose answer can legitimately be no.
 */
export const dockerShell: Shell = (args, stdin) =>
  new Promise((resolve, reject) => {
    const child = spawn('docker', [...args], { stdio: ['pipe', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
    child.stdout.on('data', (chunk: string) => {
      stdout += chunk;
    });
    child.stderr.on('data', (chunk: string) => {
      stderr += chunk;
    });

    child.on('error', () => {
      reject(
        new CliError('Could not run docker.', {
          hint: 'A local run needs Docker on this machine. Install it, or start Docker Desktop.',
        }),
      );
    });
    child.on('close', (code) => resolve({ stdout, stderr, code: code ?? 1 }));

    // Closed either way. Without the end() a command that reads nothing still holds
    // an open pipe, and `docker exec -i` waits on it.
    child.stdin.on('error', () => {});
    if (stdin !== undefined) child.stdin.write(stdin);
    child.stdin.end();
  });

/**
 * The per-runtime facts a local run needs, which the cloud keeps in its own table.
 *
 * Short on purpose, and every entry here is something the API should be handing us:
 * `/agents/runtimes` already returns the image and the release it was verified at,
 * and the rest of the backend's `BRAIN_RUNTIMES` record is the same kind of fact.
 * Until it does, this is the smallest set that brings a container up, and `home` is
 * read off the image where the image publishes it rather than written down twice.
 */
interface LocalRuntime {
  /** An image environment variable naming the agent's directory, when there is one. */
  homeFromEnv: string | null;
  /** Otherwise, a path under the container user's own home. */
  homeUnderUser: string | null;
  /** Where the runtime reads its instructions, relative to home. */
  systemPromptFile: string;
  /** Kept idle so provisioning can write into it before anything starts. */
  idleCommand: string;
  /** How to talk to the agent once the project is in place. */
  interactive: string;
}

export const LOCAL_RUNTIMES: Readonly<Record<string, LocalRuntime>> = {
  hermes: {
    homeFromEnv: 'HERMES_HOME',
    homeUnderUser: null,
    systemPromptFile: 'SOUL.md',
    idleCommand: 'sleep infinity',
    interactive: 'hermes',
  },
  openclaw: {
    homeFromEnv: null,
    homeUnderUser: '.openclaw',
    systemPromptFile: 'workspace/AGENTS.md',
    idleCommand: 'sleep infinity',
    interactive: 'openclaw',
  },
};

export function localRuntime(brain: string): LocalRuntime {
  const runtime = LOCAL_RUNTIMES[brain];
  if (!runtime) {
    throw new CliError(`No local runtime for brain '${brain}'.`, {
      hint: `Runnable here: ${Object.keys(LOCAL_RUNTIMES).join(', ')}. Run 'agent runtimes' for the full list.`,
    });
  }
  return runtime;
}

/** One container per project, named so it is obvious who made it and for what. */
export function containerName(id: string): string {
  return `agentkit-${id}`;
}

/**
 * `{{key}}` and `{{key | fallback}}`, resolved from what the caller knows.
 *
 * The cloud fills these from the answers someone typed into the wizard. Locally the
 * answers come from `.env.local`, and the only value this module supplies itself is
 * `home`, which is the runtime's, not the author's. A placeholder with no answer is
 * left standing rather than blanked: an agent whose script silently lost a path is
 * harder to debug than one that visibly still has a `{{...}}` in it, and the caller
 * reports every one it left behind.
 */
export function resolvePlaceholders(
  text: string,
  values: ReadonlyMap<string, string>,
): { text: string; unresolved: string[] } {
  const unresolved = new Set<string>();
  const resolved = text.replace(/\{\{([^{}]+)\}\}/g, (whole, body: string) => {
    for (const term of body.split('|').map((part) => part.trim())) {
      // A quoted term is a literal default, which is an answer in itself.
      const literal = /^"(.*)"$|^'(.*)'$/.exec(term);
      if (literal) return literal[1] ?? literal[2] ?? '';
      const value = values.get(term);
      if (value !== undefined && value.length > 0) return value;
    }
    // Reported by its first term, which is the field an author would go and answer.
    // The rest of a `{{a | b | "c"}}` chain is the platform's own fallback, and naming
    // all of it reads like three separate things are missing.
    unresolved.add(body.split('|')[0]?.trim() ?? body.trim());
    return whole;
  });
  return { text: resolved, unresolved: [...unresolved] };
}

/**
 * The answers a local run has, read from `.env.local`.
 *
 * That file is the container's environment, so its names are environment names, while
 * a placeholder in a project is a config field: `TEAM_NAME=Platform` is the answer to
 * `{{teamName}}`. Both spellings go into the map so an author writes the field name
 * once, in the project, and the value once, in the file that is not committed.
 */
export function answersFrom(envBody: string): Map<string, string> {
  const values = new Map<string, string>();
  for (const line of envBody.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (trimmed.length === 0 || trimmed.startsWith('#')) continue;
    const at = trimmed.indexOf('=');
    if (at === -1) continue;
    const key = trimmed.slice(0, at).trim();
    const value = trimmed.slice(at + 1).trim();
    values.set(key, value);
    const camel = toCamelCase(key);
    if (!values.has(camel)) values.set(camel, value);
  }
  return values;
}

/** `TEAM_NAME` is how an environment spells `teamName`. */
export function toCamelCase(key: string): string {
  const parts = key.toLowerCase().split('_').filter(Boolean);
  return parts
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
}

export interface Container {
  name: string;
  image: string;
  home: string;
  brain: string;
  /** `uid:gid` of the home directory, which is who the agent itself is. */
  user: string;
}

/** `running`, `exited`, or null when there is no such container. */
export async function containerState(shell: Shell, name: string): Promise<string | null> {
  // `container inspect` rather than `inspect`, which also resolves image names and
  // would answer about an image that happened to share the name.
  const result = await shell(['container', 'inspect', '--format', '{{.State.Status}}', name]);
  return result.code === 0 ? result.stdout.trim() : null;
}

/**
 * Start the runtime idle, so the project can be written into it before it boots.
 *
 * The cloud does the same thing for the same reason: an agent that starts with the
 * image's stock identity and reads its soul a second later has already answered a
 * message as somebody else.
 */
export async function startContainer(
  shell: Shell,
  options: { name: string; image: string; brain: string },
): Promise<void> {
  const runtime = localRuntime(options.brain);
  const result = await shell([
    'run',
    '--detach',
    '--name',
    options.name,
    options.image,
    ...runtime.idleCommand.split(' '),
  ]);
  if (result.code !== 0) {
    throw new CliError(`Could not start the container: ${firstLine(result.stderr)}`, {
      hint: `Remove anything left over with 'agent run --down' and try again.`,
    });
  }
}

const ROOT = '0:0';

/**
 * Who the agent is inside its container, read off the directory it owns.
 *
 * Read twice, because this exact question is what took a deploy down once: the image's
 * own init chowns that directory from a service that runs alongside us, so a single
 * early read can answer root, and everything written afterwards is then chowned to
 * root and unreadable by the agent. Two agreeing reads mean it has stopped changing
 * hands. A directory that stays root's is legal, so that is waited on and then
 * accepted rather than refused; one that cannot be read at all is not, because
 * guessing root there is how the failure happens in the first place.
 */
export async function userOf(shell: Shell, name: string, home: string): Promise<string> {
  let last = '';
  for (let attempt = 0; attempt < 6; attempt++) {
    const found = await shell(['exec', name, 'stat', '-c', '%u:%g', home]);
    const value = found.code === 0 ? found.stdout.trim() : '';
    if (/^\d+:\d+$/.test(value)) {
      if (value === last && value !== ROOT) return value;
      last = value;
      // No wait before confirming a settled answer: an exec is itself a gap, and this
      // runs on every local run. The waiting below is for when there is a reason.
      if (value !== ROOT) continue;
    } else {
      last = '';
    }
    await pause(250);
  }

  if (last === '') {
    throw new CliError(`Could not tell who owns ${home} in the container.`, {
      hint: 'The image may have changed. Run `agent runtimes` to see which release is verified.',
    });
  }
  return last;
}

/** Only ever waited on while a container's own init is still moving underneath us. */
function pause(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Where the agent's own directory is, asked of the container rather than assumed.
 *
 * Hermes publishes `HERMES_HOME` in the image, so that is read back from the running
 * container: a path this package wrote down instead would be a second source of truth
 * for something the image already states. OpenClaw does not publish one, so its
 * directory is resolved under whatever `$HOME` the image's own user has.
 */
export async function homeOf(shell: Shell, name: string, brain: string): Promise<string> {
  const runtime = localRuntime(brain);
  if (runtime.homeFromEnv) {
    const found = await shell(['exec', name, 'printenv', runtime.homeFromEnv]);
    const value = found.stdout.trim();
    if (found.code === 0 && value.startsWith('/')) return value;
  }
  if (runtime.homeUnderUser) {
    const found = await shell(['exec', name, 'printenv', 'HOME']);
    const value = found.stdout.trim();
    if (found.code === 0 && value.startsWith('/')) {
      return posix.join(value, runtime.homeUnderUser);
    }
  }
  throw new CliError(`Could not tell where a ${brain} agent keeps its files.`, {
    hint: 'The image may have changed. Run `agent runtimes` to see which release is verified.',
  });
}

/**
 * Write one file into the container, then hand it to the user the runtime runs as.
 *
 * `docker exec` is root and the runtime is not, so a file written without the chown
 * arrives owned by root and mode 600, and the agent cannot read its own soul or run
 * its own script. That failure is invisible: the container starts, the agent answers,
 * and it answers as the image's default identity because the file it would have read
 * was unreadable. The cloud learned this the same way and does the same thing, and
 * the owner is read off the home directory rather than named because each image has
 * its own user.
 */
export async function writeFile(
  shell: Shell,
  container: Container,
  path: string,
  contents: string,
): Promise<void> {
  const dir = posix.dirname(path);
  const script =
    `set -e\n` +
    `mkdir -p ${quote(dir)}\n` +
    `cat > ${quote(path)}\n`;
  const written = await shell(['exec', '-i', container.name, 'sh', '-c', script], contents);
  if (written.code !== 0) {
    throw new CliError(`Could not write ${path}: ${firstLine(written.stderr)}`);
  }

  // The owner settled on once, rather than stat'd again per file: a second reading can
  // differ from the first while the image's init is still running, and then the files
  // are owned by one user while the commands below run as another.
  const target = dir.startsWith(`${container.home}/`) ? dir : path;
  await shell(['exec', container.name, 'chown', '-R', container.user, target]);
}

/**
 * The environment, read the way the runtime reads it rather than executed.
 *
 * `.env` has to reach a setup script and a test somehow, and the obvious way, sourcing
 * it, is wrong in three ways that all pass silently. `TEAM_NAME=Platform Engineering`
 * makes the variable *empty* and prints a stray `Engineering: not found`; a value
 * containing `$OTHER` gets expanded; and `$(...)` in a value would simply run. The
 * runtime uses a dotenv reader, which does none of that, and the whole point of a local
 * run is that the command sees what the agent sees. So the file is parsed: each line
 * split at the first `=`, one layer of surrounding quotes removed the way dotenv
 * removes it, and the pair handed to `export` as a single word.
 */
const READ_ENV: readonly string[] = [
  'if [ -r .env ]; then',
  '  while IFS= read -r line || [ -n "$line" ]; do',
  "    case \"$line\" in ''|'#'*) continue ;; *=*) ;; *) continue ;; esac",
  '    name=${line%%=*}',
  '    value=${line#*=}',
  '    case "$value" in',
  '      \'"\'*\'"\') value=${value#\'"\'}; value=${value%\'"\'} ;;',
  '      "\'"*"\'") value=${value#"\'"}; value=${value%"\'"} ;;',
  '    esac',
  '    export "$name=$value"',
  '  done < .env',
  'fi',
];

/**
 * Run a command as the agent, with the agent's environment, from the agent's home.
 *
 * All three matter. `--user` because a file the agent cannot read is the failure this
 * whole module is careful about, and a check run as root would not see it. The home
 * directory because that is where a project's own paths are relative to. The
 * environment because `.env` is a file the runtime reads for itself, so a command run
 * beside the runtime gets nothing from it unless it reads it too, and a variable
 * missing here looks exactly like a variable that was never set.
 */
export async function runAsAgent(
  shell: Shell,
  container: Container,
  command: string,
): Promise<ShellResult> {
  const preamble = [`cd ${quote(container.home)}`, ...READ_ENV, ''].join('\n');
  return shell([
    'exec',
    '--user',
    container.user,
    container.name,
    'sh',
    '-c',
    preamble + command,
  ]);
}

/** Exported for a test that runs it against a real `sh`, which is the only proof. */
export function readEnvScript(): string {
  return READ_ENV.join('\n');
}

export async function removeContainer(shell: Shell, name: string): Promise<boolean> {
  const result = await shell(['rm', '--force', '--volumes', name]);
  return result.code === 0;
}

/** Single-quote a path for `sh -c`, the one escape being a doubled quote. */
function quote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export function firstLine(text: string): string {
  const line = text.trim().split('\n').find((part) => part.trim().length > 0);
  return line?.trim() ?? 'no output';
}
